name: build
on: [ pull_request, push ]

jobs:
  build-iris:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: 18
          
      - name: add mods folder
        run:  mkdir ../mods  
        
      - name: Cache Brachyura directory
        uses: actions/cache@v2
        with:
          path: |
            Iris/.brachyura
            ~.brachyura
          key: ${{ runner.os }}-brachyura-${{ hashFiles('**/Buildscript.java') }}
          restore-keys: ${{ runner.os }}-brachyura

      - name: Build with Brachyura
        run: java -jar brachyura-bootstrap-0.jar build
        
      - name: copy mods
        run: cp $(ls Iris/build/libs | grep -oP '^(?!.*sources)(?!.*dirty)(?!.*dev).*') ./mods
  build-sodium:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: add mods folder    
        run:  mkdir ../mods  
        
      - name: chmod gradlew
        run: chmod +x sodium-fabric/gradlew
      - name: compile sodium
        run: sodium-fabric/gradlew build
  
      - name: copy mods
        run: cp $(ls sodium-fabric/build/libs | grep -oP '^(?!.*sources)(?!.*dirty)(?!.*dev).*') ./mods
  release:
    runs-on: ubuntu-latest
    needs: [build-sodium, build-iris]
    steps:
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: mods/
