name: build
on: [ pull_request, push ]

jobs:
  build-iris:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: 18
          
      - name: add mods folder
        run:  mkdir mods  

      - name: Build with Brachyura
        run: java -jar Iris/brachyura-bootstrap-0.jar build
        
      - name: copy mods
        run: |
          cp Iris/build/libs/$(ls Iris/build/libs | grep -oP '^(?!.*sources)(?!.*dirty)(?!.*dev).*') ./mods
  build-sodium:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: 18
        
      - name: chmod gradlew
        run: chmod +x sodium-fabric/gradlew
        
      - name: compile sodium
        run: |
          cd sodium-fabric/
          ./gradlew build
  
      - name: copy mods
        run: cp sodium-fabric/build/libs/$(ls sodium-fabric/build/libs | grep -oP '^(?!.*sources)(?!.*dirty)(?!.*dev).*') ./mods
  release:
    runs-on: ubuntu-latest
    needs: [build-sodium, build-iris]
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: ./mods
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: mods/
